### ISSUE TITLE
Exception (NRE) when trying to rename an access entry

### ISSUE THREAD

**Issue by sprucely** [ucdavis/Peaks#1233]
Tried to change the name and description of https://peaks.ucdavis.edu/caes-cru/access/details/1341. Logs show a NullReferenceException...
```
   at Keas.Core.Domain.AssetBase.GetDescription(String asset, String title, Person person, String action, String extraSpaceInfo) in D:\a\1\s\Keas.Core\Domain\AssetBase.cs:line 39
   at Keas.Mvc.Services.HistoryService.AccessUpdated(Access access) in D:\a\1\s\Keas.Mvc\Services\HistoryService.cs:line 162
   at Keas.Mvc.Services.EventService.TrackUpdateAccess(Access access) in D:\a\1\s\Keas.Mvc\Services\EventService.cs:line 139
   at Keas.Mvc.Controllers.Api.AccessController.Update(Access access) in D:\a\1\s\Keas.Mvc\Controllers\Api\AccessController.cs:line 233
   ...
```

**Comment by sprucely** [comment]
Never mind. DB was missing a People record for me, which is a state it won't reach outside of direct db editing shenanigans.
